"""Create Activity table and archive old tables

Revision ID: 0eec56bb8a7c
Revises: d25490bc192c
Create Date: 2025-10-30 17:37:37.065862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eec56bb8a7c'
down_revision: Union[str, Sequence[str], None] = 'd25490bc192c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Archive old tables by renaming them
    op.rename_table('heart_rate_data', 'heart_rate_data_archived')
    op.rename_table('exercise_sessions', 'exercise_sessions_archived')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strava_id', sa.String(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('is_onsen_monitoring', sa.Boolean(), nullable=False),
    sa.Column('recording_start', sa.DateTime(), nullable=False),
    sa.Column('recording_end', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=True),
    sa.Column('workout_type', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('min_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(), nullable=True),
    sa.Column('weather_conditions', sa.String(), nullable=True),
    sa.Column('route_data', sa.String(), nullable=True),
    sa.Column('strava_data_hash', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['onsen_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_recording_start'), 'activities', ['recording_start'], unique=False)
    op.create_index(op.f('ix_activities_strava_id'), 'activities', ['strava_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_strava_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_recording_start'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###

    # Restore old tables from archive
    op.rename_table('exercise_sessions_archived', 'exercise_sessions')
    op.rename_table('heart_rate_data_archived', 'heart_rate_data')
