"""Remove time_of_day from visit table

Revision ID: 3b6ec50e10ad
Revises: 8ffe71584c02
Create Date: 2025-10-30 18:33:52.310117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6ec50e10ad'
down_revision: Union[str, Sequence[str], None] = '8ffe71584c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onsen_visits', schema=None) as batch_op:
        batch_op.drop_column('time_of_day')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onsen_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_day', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
