"""Remove exercise columns from visit table

Revision ID: 62c926c2f8af
Revises: 0eec56bb8a7c
Create Date: 2025-10-30 18:12:24.733023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c926c2f8af'
down_revision: Union[str, Sequence[str], None] = '0eec56bb8a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_sessions_exercise_type'), table_name='exercise_sessions_archived')
    op.drop_index(op.f('ix_exercise_sessions_recording_start'), table_name='exercise_sessions_archived')
    op.create_index(op.f('ix_exercise_sessions_archived_exercise_type'), 'exercise_sessions_archived', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercise_sessions_archived_recording_start'), 'exercise_sessions_archived', ['recording_start'], unique=False)
    op.drop_column('onsen_visits', 'exercise_type')
    op.drop_column('onsen_visits', 'exercise_before_onsen')
    op.drop_column('onsen_visits', 'exercise_length_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onsen_visits', sa.Column('exercise_length_minutes', sa.INTEGER(), nullable=True))
    op.add_column('onsen_visits', sa.Column('exercise_before_onsen', sa.BOOLEAN(), nullable=True))
    op.add_column('onsen_visits', sa.Column('exercise_type', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_exercise_sessions_archived_recording_start'), table_name='exercise_sessions_archived')
    op.drop_index(op.f('ix_exercise_sessions_archived_exercise_type'), table_name='exercise_sessions_archived')
    op.create_index(op.f('ix_exercise_sessions_recording_start'), 'exercise_sessions_archived', ['recording_start'], unique=False)
    op.create_index(op.f('ix_exercise_sessions_exercise_type'), 'exercise_sessions_archived', ['exercise_type'], unique=False)
    # ### end Alembic commands ###
