"""Add weight_measurements table

Revision ID: 75f5027ba821
Revises: 3b6ec50e10ad
Create Date: 2025-10-30 19:25:13.037728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f5027ba821'
down_revision: Union[str, Sequence[str], None] = '3b6ec50e10ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measurement_time', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('measurement_conditions', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_file_path', sa.String(), nullable=True),
    sa.Column('data_hash', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_measurements_measurement_time'), ['measurement_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_measurements_measurement_time'))

    op.drop_table('weight_measurements')
    # ### end Alembic commands ###
