"""Add RuleRevision table

Revision ID: 84ec13236678
Revises: 
Create Date: 2025-10-13 12:20:06.270129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ec13236678'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('revision_date', sa.DateTime(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('week_start_date', sa.String(), nullable=False),
    sa.Column('week_end_date', sa.String(), nullable=False),
    sa.Column('onsen_visits_count', sa.Integer(), nullable=True),
    sa.Column('total_soaking_hours', sa.Float(), nullable=True),
    sa.Column('sauna_sessions_count', sa.Integer(), nullable=True),
    sa.Column('running_distance_km', sa.Float(), nullable=True),
    sa.Column('gym_sessions_count', sa.Integer(), nullable=True),
    sa.Column('hike_completed', sa.Boolean(), nullable=True),
    sa.Column('rest_days_count', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality_rating', sa.String(), nullable=True),
    sa.Column('soreness_notes', sa.String(), nullable=True),
    sa.Column('hydration_nutrition_notes', sa.String(), nullable=True),
    sa.Column('mood_mental_state', sa.String(), nullable=True),
    sa.Column('reflection_positive', sa.String(), nullable=True),
    sa.Column('reflection_patterns', sa.String(), nullable=True),
    sa.Column('reflection_warnings', sa.String(), nullable=True),
    sa.Column('reflection_standout_onsens', sa.String(), nullable=True),
    sa.Column('reflection_routine_notes', sa.String(), nullable=True),
    sa.Column('adjustment_reason', sa.String(), nullable=True),
    sa.Column('adjustment_description', sa.String(), nullable=True),
    sa.Column('expected_duration', sa.String(), nullable=True),
    sa.Column('health_safeguard_applied', sa.String(), nullable=True),
    sa.Column('next_week_focus', sa.String(), nullable=True),
    sa.Column('next_week_goals', sa.String(), nullable=True),
    sa.Column('next_week_sauna_limit', sa.Integer(), nullable=True),
    sa.Column('next_week_run_volume', sa.Float(), nullable=True),
    sa.Column('next_week_hike_destination', sa.String(), nullable=True),
    sa.Column('sections_modified', sa.String(), nullable=True),
    sa.Column('revision_summary', sa.String(), nullable=True),
    sa.Column('markdown_file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_revisions')
    # ### end Alembic commands ###
