"""Remove previous_location and next_location from visit table

Revision ID: 8ffe71584c02
Revises: 62c926c2f8af
Create Date: 2025-10-30 18:21:55.161891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffe71584c02'
down_revision: Union[str, Sequence[str], None] = '62c926c2f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onsen_visits', type_='foreignkey')
    op.drop_constraint(None, 'onsen_visits', type_='foreignkey')
    op.drop_column('onsen_visits', 'previous_location')
    op.drop_column('onsen_visits', 'next_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onsen_visits', sa.Column('next_location', sa.INTEGER(), nullable=True))
    op.add_column('onsen_visits', sa.Column('previous_location', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'onsen_visits', 'onsen_visits', ['previous_location'], ['id'])
    op.create_foreign_key(None, 'onsen_visits', 'onsen_visits', ['next_location'], ['id'])
    # ### end Alembic commands ###
