"""Add notes field to onsen_visits table

Revision ID: a5449e85bc5a
Revises: ceb486dad496
Create Date: 2025-10-21 08:39:32.478362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5449e85bc5a'
down_revision: Union[str, Sequence[str], None] = 'ceb486dad496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onsen_visits', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onsen_visits', 'notes')
    # ### end Alembic commands ###
