"""Make Activity strava_id and strava_data_hash nullable

Revision ID: bc54de4d293d
Revises: 6af9dac9e8ea
Create Date: 2025-11-06 12:26:24.147557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc54de4d293d'
down_revision: Union[str, Sequence[str], None] = '6af9dac9e8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('strava_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strava_data_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('strava_data_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('strava_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
