"""Add exercise_sessions table

Revision ID: ceb486dad496
Revises: 84ec13236678
Create Date: 2025-10-21 08:20:30.886470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb486dad496'
down_revision: Union[str, Sequence[str], None] = '84ec13236678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('heart_rate_id', sa.Integer(), nullable=True),
    sa.Column('recording_start', sa.DateTime(), nullable=False),
    sa.Column('recording_end', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=True),
    sa.Column('workout_type', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_file_path', sa.String(), nullable=True),
    sa.Column('data_hash', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('min_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(), nullable=True),
    sa.Column('weather_conditions', sa.String(), nullable=True),
    sa.Column('route_data', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['heart_rate_id'], ['heart_rate_data.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['onsen_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_sessions_exercise_type'), 'exercise_sessions', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercise_sessions_recording_start'), 'exercise_sessions', ['recording_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_sessions_recording_start'), table_name='exercise_sessions')
    op.drop_index(op.f('ix_exercise_sessions_exercise_type'), table_name='exercise_sessions')
    op.drop_table('exercise_sessions')
    # ### end Alembic commands ###
