"""Add local interaction tracking and remove water type

Revision ID: d25490bc192c
Revises: f95050c7bb07
Create Date: 2025-10-30 10:20:45.725594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25490bc192c'
down_revision: Union[str, Sequence[str], None] = 'f95050c7bb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onsen_visits', sa.Column('interacted_with_locals', sa.Boolean(), nullable=True))
    op.add_column('onsen_visits', sa.Column('local_interaction_quality_rating', sa.Integer(), nullable=True))
    op.drop_column('onsen_visits', 'main_bath_water_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onsen_visits', sa.Column('main_bath_water_type', sa.VARCHAR(), nullable=True))
    op.drop_column('onsen_visits', 'local_interaction_quality_rating')
    op.drop_column('onsen_visits', 'interacted_with_locals')
    # ### end Alembic commands ###
